Feature/hht 1046 link dataset to model
HIRO-MicroDataCenters-BV/cog-framework-ui pull request #84
Opened 2024-11-20 14:57 UTC by Kagameow

2024-11-21 11:34 UTC, kaaboeld requested changes

2024-11-21 11:34 UTC, kaaboeld commented on src/app/components/model-dataset-link/model-dataset-link.component.ts
> +    this.snackBar.open(message, action, {
Maybe move this to consts?

2024-11-21 11:34 UTC, kaaboeld commented on src/app/pages/model-detail/model-datasets/model-datasets.component.html
>              [dataSource]="modelDatasetDataSource"
Rename:
`modelDatasetDataSource > dataSource`

Redata:
`modelDatasetDataSource: ModelDatasetInfo[] = []; > dataSource = new MatTableDataSource<DatasetData>([]);`

2024-11-21 11:34 UTC, kaaboeld commented on src/app/pages/model-detail/model-datasets/model-datasets.component.ts
>    modelDatasetDataSource: ModelDatasetInfo[] = [];
Up

2024-11-21 11:34 UTC, kaaboeld commented on src/app/pages/model-detail/model-datasets/model-datasets.component.ts
> +    this.snackBar.open(message, action, {
Up

2024-11-26 10:30 UTC, Kagameow commented
I'll merge since I'm a little blocked. Please, Eugene, let me know if there are any other issues regarding the pr, I will fix them in a separate pr.

2024-11-26 10:31 UTC, merged